DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS jobs;

CREATE TABLE person (
    id INT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(45) NOT NULL,
    last_name VARCHAR(45) NOT NULL
);

CREATE TABLE job (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    position VARCHAR(255) NOT NULL,
    field VARCHAR(255) NOT NULL,
    seniority VARCHAR(255) NOT NULL
);